apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-creator
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-creator-binding
subjects:
- kind: ServiceAccount
  name: demo-k8s
  namespace: demo-k8s
roleRef:
  kind: ClusterRole
  name: crd-creator
  apiGroup: rbac.authorization.k8s.io